// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type Action string

const (
	Action_ALERT Action = "ALERT"
	Action_ALLOW Action = "ALLOW"
	Action_BLOCK Action = "BLOCK"
)

type AutodefinedReverseFlag string

const (
	AutodefinedReverseFlag_DISABLE                    AutodefinedReverseFlag = "DISABLE"
	AutodefinedReverseFlag_ENABLE                     AutodefinedReverseFlag = "ENABLE"
	AutodefinedReverseFlag_USE_LOCAL_RESOURCE_SETTING AutodefinedReverseFlag = "USE_LOCAL_RESOURCE_SETTING"
)

type BlockOverrideDNSType string

const (
	BlockOverrideDNSType_CNAME BlockOverrideDNSType = "CNAME"
)

type BlockResponse string

const (
	BlockResponse_NODATA   BlockResponse = "NODATA"
	BlockResponse_NXDOMAIN BlockResponse = "NXDOMAIN"
	BlockResponse_OVERRIDE BlockResponse = "OVERRIDE"
)

type ConfidenceThreshold string

const (
	ConfidenceThreshold_HIGH   ConfidenceThreshold = "HIGH"
	ConfidenceThreshold_LOW    ConfidenceThreshold = "LOW"
	ConfidenceThreshold_MEDIUM ConfidenceThreshold = "MEDIUM"
)

type DNSThreatProtection string

const (
	DNSThreatProtection_DGA           DNSThreatProtection = "DGA"
	DNSThreatProtection_DNS_TUNNELING DNSThreatProtection = "DNS_TUNNELING"
)

type FirewallDomainImportOperation string

const (
	FirewallDomainImportOperation_REPLACE FirewallDomainImportOperation = "REPLACE"
)

type FirewallDomainListStatus string

const (
	FirewallDomainListStatus_COMPLETE               FirewallDomainListStatus = "COMPLETE"
	FirewallDomainListStatus_COMPLETE_IMPORT_FAILED FirewallDomainListStatus = "COMPLETE_IMPORT_FAILED"
	FirewallDomainListStatus_DELETING               FirewallDomainListStatus = "DELETING"
	FirewallDomainListStatus_IMPORTING              FirewallDomainListStatus = "IMPORTING"
	FirewallDomainListStatus_UPDATING               FirewallDomainListStatus = "UPDATING"
)

type FirewallDomainRedirectionAction string

const (
	FirewallDomainRedirectionAction_INSPECT_REDIRECTION_DOMAIN FirewallDomainRedirectionAction = "INSPECT_REDIRECTION_DOMAIN"
	FirewallDomainRedirectionAction_TRUST_REDIRECTION_DOMAIN   FirewallDomainRedirectionAction = "TRUST_REDIRECTION_DOMAIN"
)

type FirewallDomainUpdateOperation string

const (
	FirewallDomainUpdateOperation_ADD     FirewallDomainUpdateOperation = "ADD"
	FirewallDomainUpdateOperation_REMOVE  FirewallDomainUpdateOperation = "REMOVE"
	FirewallDomainUpdateOperation_REPLACE FirewallDomainUpdateOperation = "REPLACE"
)

type FirewallFailOpenStatus string

const (
	FirewallFailOpenStatus_DISABLED                   FirewallFailOpenStatus = "DISABLED"
	FirewallFailOpenStatus_ENABLED                    FirewallFailOpenStatus = "ENABLED"
	FirewallFailOpenStatus_USE_LOCAL_RESOURCE_SETTING FirewallFailOpenStatus = "USE_LOCAL_RESOURCE_SETTING"
)

type FirewallRuleGroupAssociationStatus string

const (
	FirewallRuleGroupAssociationStatus_COMPLETE FirewallRuleGroupAssociationStatus = "COMPLETE"
	FirewallRuleGroupAssociationStatus_DELETING FirewallRuleGroupAssociationStatus = "DELETING"
	FirewallRuleGroupAssociationStatus_UPDATING FirewallRuleGroupAssociationStatus = "UPDATING"
)

type FirewallRuleGroupStatus string

const (
	FirewallRuleGroupStatus_COMPLETE FirewallRuleGroupStatus = "COMPLETE"
	FirewallRuleGroupStatus_DELETING FirewallRuleGroupStatus = "DELETING"
	FirewallRuleGroupStatus_UPDATING FirewallRuleGroupStatus = "UPDATING"
)

type IPAddressStatus string

const (
	IPAddressStatus_Attached               IPAddressStatus = "Attached"
	IPAddressStatus_Attaching              IPAddressStatus = "Attaching"
	IPAddressStatus_Creating               IPAddressStatus = "Creating"
	IPAddressStatus_DeleteFailedFasExpired IPAddressStatus = "DeleteFailedFasExpired"
	IPAddressStatus_Deleting               IPAddressStatus = "Deleting"
	IPAddressStatus_Detaching              IPAddressStatus = "Detaching"
	IPAddressStatus_FailedCreation         IPAddressStatus = "FailedCreation"
	IPAddressStatus_FailedResourceGone     IPAddressStatus = "FailedResourceGone"
	IPAddressStatus_RemapAttaching         IPAddressStatus = "RemapAttaching"
	IPAddressStatus_RemapDetaching         IPAddressStatus = "RemapDetaching"
	IPAddressStatus_UpdateFailed           IPAddressStatus = "UpdateFailed"
	IPAddressStatus_Updating               IPAddressStatus = "Updating"
)

type MutationProtectionStatus string

const (
	MutationProtectionStatus_DISABLED MutationProtectionStatus = "DISABLED"
	MutationProtectionStatus_ENABLED  MutationProtectionStatus = "ENABLED"
)

type OutpostResolverStatus string

const (
	OutpostResolverStatus_ACTION_NEEDED   OutpostResolverStatus = "ACTION_NEEDED"
	OutpostResolverStatus_CREATING        OutpostResolverStatus = "CREATING"
	OutpostResolverStatus_DELETING        OutpostResolverStatus = "DELETING"
	OutpostResolverStatus_FAILED_CREATION OutpostResolverStatus = "FAILED_CREATION"
	OutpostResolverStatus_FAILED_DELETION OutpostResolverStatus = "FAILED_DELETION"
	OutpostResolverStatus_OPERATIONAL     OutpostResolverStatus = "OPERATIONAL"
	OutpostResolverStatus_UPDATING        OutpostResolverStatus = "UPDATING"
)

type Protocol string

const (
	Protocol_DO53    Protocol = "DO53"
	Protocol_DOH     Protocol = "DOH"
	Protocol_DOHFIPS Protocol = "DOHFIPS"
)

type ResolverAutodefinedReverseStatus string

const (
	ResolverAutodefinedReverseStatus_Disabled                          ResolverAutodefinedReverseStatus = "Disabled"
	ResolverAutodefinedReverseStatus_Disabling                         ResolverAutodefinedReverseStatus = "Disabling"
	ResolverAutodefinedReverseStatus_Enabled                           ResolverAutodefinedReverseStatus = "Enabled"
	ResolverAutodefinedReverseStatus_Enabling                          ResolverAutodefinedReverseStatus = "Enabling"
	ResolverAutodefinedReverseStatus_UpdatingToUseLocalResourceSetting ResolverAutodefinedReverseStatus = "UpdatingToUseLocalResourceSetting"
	ResolverAutodefinedReverseStatus_UseLocalResourceSetting           ResolverAutodefinedReverseStatus = "UseLocalResourceSetting"
)

type ResolverDNSSECValidationStatus string

const (
	ResolverDNSSECValidationStatus_Disabled                        ResolverDNSSECValidationStatus = "Disabled"
	ResolverDNSSECValidationStatus_Disabling                       ResolverDNSSECValidationStatus = "Disabling"
	ResolverDNSSECValidationStatus_Enabled                         ResolverDNSSECValidationStatus = "Enabled"
	ResolverDNSSECValidationStatus_Enabling                        ResolverDNSSECValidationStatus = "Enabling"
	ResolverDNSSECValidationStatus_UpdateToUseLocalResourceSetting ResolverDNSSECValidationStatus = "UpdateToUseLocalResourceSetting"
	ResolverDNSSECValidationStatus_UseLocalResourceSetting         ResolverDNSSECValidationStatus = "UseLocalResourceSetting"
)

type ResolverEndpointDirection string

const (
	ResolverEndpointDirection_Inbound  ResolverEndpointDirection = "Inbound"
	ResolverEndpointDirection_Outbound ResolverEndpointDirection = "Outbound"
)

type ResolverEndpointStatus_SDK string

const (
	ResolverEndpointStatus_SDK_ActionNeeded   ResolverEndpointStatus_SDK = "ActionNeeded"
	ResolverEndpointStatus_SDK_AutoRecovering ResolverEndpointStatus_SDK = "AutoRecovering"
	ResolverEndpointStatus_SDK_Creating       ResolverEndpointStatus_SDK = "Creating"
	ResolverEndpointStatus_SDK_Deleting       ResolverEndpointStatus_SDK = "Deleting"
	ResolverEndpointStatus_SDK_Operational    ResolverEndpointStatus_SDK = "Operational"
	ResolverEndpointStatus_SDK_Updating       ResolverEndpointStatus_SDK = "Updating"
)

type ResolverEndpointType string

const (
	ResolverEndpointType_DUALSTACK ResolverEndpointType = "DUALSTACK"
	ResolverEndpointType_IPV4      ResolverEndpointType = "IPV4"
	ResolverEndpointType_IPV6      ResolverEndpointType = "IPV6"
)

type ResolverQueryLogConfigAssociationError string

const (
	ResolverQueryLogConfigAssociationError_AccessDenied         ResolverQueryLogConfigAssociationError = "AccessDenied"
	ResolverQueryLogConfigAssociationError_DestinationNotFound  ResolverQueryLogConfigAssociationError = "DestinationNotFound"
	ResolverQueryLogConfigAssociationError_InternalServiceError ResolverQueryLogConfigAssociationError = "InternalServiceError"
	ResolverQueryLogConfigAssociationError_None                 ResolverQueryLogConfigAssociationError = "None"
)

type ResolverQueryLogConfigAssociationStatus string

const (
	ResolverQueryLogConfigAssociationStatus_ActionNeeded ResolverQueryLogConfigAssociationStatus = "ActionNeeded"
	ResolverQueryLogConfigAssociationStatus_Active       ResolverQueryLogConfigAssociationStatus = "Active"
	ResolverQueryLogConfigAssociationStatus_Creating     ResolverQueryLogConfigAssociationStatus = "Creating"
	ResolverQueryLogConfigAssociationStatus_Deleting     ResolverQueryLogConfigAssociationStatus = "Deleting"
	ResolverQueryLogConfigAssociationStatus_Failed       ResolverQueryLogConfigAssociationStatus = "Failed"
)

type ResolverQueryLogConfigStatus string

const (
	ResolverQueryLogConfigStatus_Created  ResolverQueryLogConfigStatus = "Created"
	ResolverQueryLogConfigStatus_Creating ResolverQueryLogConfigStatus = "Creating"
	ResolverQueryLogConfigStatus_Deleting ResolverQueryLogConfigStatus = "Deleting"
	ResolverQueryLogConfigStatus_Failed   ResolverQueryLogConfigStatus = "Failed"
)

type ResolverRuleAssociationStatus string

const (
	ResolverRuleAssociationStatus_Complete   ResolverRuleAssociationStatus = "Complete"
	ResolverRuleAssociationStatus_Creating   ResolverRuleAssociationStatus = "Creating"
	ResolverRuleAssociationStatus_Deleting   ResolverRuleAssociationStatus = "Deleting"
	ResolverRuleAssociationStatus_Failed     ResolverRuleAssociationStatus = "Failed"
	ResolverRuleAssociationStatus_Overridden ResolverRuleAssociationStatus = "Overridden"
)

type ResolverRuleStatus_SDK string

const (
	ResolverRuleStatus_SDK_Complete ResolverRuleStatus_SDK = "Complete"
	ResolverRuleStatus_SDK_Deleting ResolverRuleStatus_SDK = "Deleting"
	ResolverRuleStatus_SDK_Failed   ResolverRuleStatus_SDK = "Failed"
	ResolverRuleStatus_SDK_Updating ResolverRuleStatus_SDK = "Updating"
)

type RuleTypeOption string

const (
	RuleTypeOption_Forward   RuleTypeOption = "Forward"
	RuleTypeOption_Recursive RuleTypeOption = "Recursive"
	RuleTypeOption_System    RuleTypeOption = "System"
)

type ShareStatus string

const (
	ShareStatus_NotShared    ShareStatus = "NotShared"
	ShareStatus_SharedByMe   ShareStatus = "SharedByMe"
	ShareStatus_SharedWithMe ShareStatus = "SharedWithMe"
)

type SortOrder string

const (
	SortOrder_Ascending  SortOrder = "Ascending"
	SortOrder_Descending SortOrder = "Descending"
)

type Validation string

const (
	Validation_DISABLE                    Validation = "DISABLE"
	Validation_ENABLE                     Validation = "ENABLE"
	Validation_USE_LOCAL_RESOURCE_SETTING Validation = "USE_LOCAL_RESOURCE_SETTING"
)
